# Generated by Django 5.0.3 on 2024-03-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vk_id", models.TextField()),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("third_name", models.TextField()),
                ("avatar", models.TextField()),
                ("is_Prepod", models.BooleanField()),
                ("is_Superuser", models.BooleanField()),
            ],
        ),
    ]
